name: Demo04
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on:
  workflow_dispatch:
workflow_dispatch: 
jobs:
  dev:
    runs-on: [ self-hosted, Linux ]
    steps:
      - name: Passo 01
        run:  echo  "Teste"
